export const GEAR_CATEGORIES = [
  {
    category: "DESK SETUP",
    items: [
      {
        id: "pc-build",
        title: "Desktop PC",
        specs: "Ryzen 7 5700X · GTX 1660S",
        image: "/Images/PC-Build.webp",
        link: "https://pcpartpicker.com",
        badge: "Primary Workstation",
      },
      {
        id: "asus-tuf",
        title: "ASUS TUF Gaming FX505DT",
        specs: "Ryzen 5 3550H · GTX 1650",
        image: "/Images/Asus-TUF-FX505DT.webp",
        link: "https://www.asus.com/laptops/for-gaming/tuf-gaming/asus-tuf-gaming-fx505dy-dd-dt-du/",
        badge: "Mobile Rig",
      },
      {
        id: "nvision-monitor",
        title: "N-Vision 24\" IPS Monitor",
        specs: "24\" 1080p IPS · 180Hz",
        image: "/Images/Nvision-Monitor.webp",
        link: "https://shopee.ph",
        badge: "Display",
      },
      {
        id: "attack-shark",
        title: "Attack Shark Mechanical Keyboard",
        specs: "Tri-mode wireless RGB.",
        image: "/Images/AttackShark-Keyboard.webp",
        link: "https://attackshark.com",
        badge: "Keyboard",
      },
      {
        id: "vxe-mouse",
        title: "VXE Wireless Gaming Mouse",
        specs: "Ultra-lightweight wireless.",
        image: "/Images/VXE-Mouse.webp",
        link: "https://shopee.ph",
        badge: "Mouse",
      },
    ],
  },
  {
    category: "AUDIO & EVERYDAY CARRY",
    items: [
      {
        id: "hyperx-headset",
        title: "HyperX Cloud Stinger Headset",
        specs: "Lightweight gaming headset.",
        image: "/Images/HyperX-Headset.webp",
        link: "https://hyperx.com",
        badge: "Headset",
      },
      {
        id: "baseus-bowie",
        title: "Baseus Bowie E16 TWS Earbuds",
        specs: "Compact TWS earbuds.",
        image: "/Images/Baseus-Bowie-E16.webp",
        link: "https://baseus.com",
        badge: "Audio",
      },
      {
        id: "iphone-13",
        title: "Apple iPhone 13",
        specs: "128GB · Midnight.",
        image: "/Images/iPhone13-Phone.webp",
        link: "https://www.apple.com/iphone-13/",
        badge: "Mobile",
      },
    ],
  },
];
